const AppTheme = {
  light: {
    jumboBackground: "#f7b2f3",
    experienceBackground: "#DBAFA0",
    expCardBackground: "#E2DFD0",
    experienceHeading: "#000",
    linkColor: "#000",
    iconColor: "#000",
    headingColor: "#000",
    subtleText: "#000",
    background: "#fff",
    foreground: "#000",
    planetColor: "yellow",
    cardBackground: "white",
    navColor: "#D3EBCD",
    aboutBackground: "#D4ECDD",
    aboutForeground: "#112031",
    aboutSectionBackground: "#ffff",
    aboutSectionForeground: "#000",
    aboutHeadingBackground: "#000",
    aboutHeadingForeground: "white",
    aboutShadow: "black",
    DrawerBackground: "#E9D5DA",
    DrawerForeground: "#363062",
    JumboHeading: "black",
    CardForeground: "black",
    ProjectBackground: "#010821",
    ProjectForeground: "#c8d3fa",
    ContactForeground: "black",
    link: "green",
    // articleBackground: "#aee7f2",
    articleCardBackground: "#fff",
    articleHeading: "#fff",
  },
  dark: {
    experienceBackground: "#49243E",
    experienceHeading: "#fff",
    iconColor: "#fff",
    subtleText: "#fff",
    headingColor: "#fff",
    expCardBackground: "#32012F",
    JumboHeading: "white",
    jumboBackground: "#2b0329",
    jumboForeground: "black",
    background: "#002B5B",
    linkColor: "#fff",
    foreground: "#fff",
    planetColor: "#e6e2d8",
    cardBackground: "#4a0d47",
    navColor: "#635666",
    aboutBackground: "#112031",
    aboutForeground: "#D4ECDD",
    aboutSectionBackground: "#081830",
    aboutSectionForeground: "white",
    aboutHeadingBackground: "white",
    aboutHeadingForeground: "black",
    aboutShadow: "white",
    DrawerBackground: "#363062",
    DrawerForeground: "#E9D5DA",
    CardForeground: "white",
    ProjectBackground: "#c8d3fa",
    ProjectForeground: "#010821",
    ContactForeground: "white",
    link: "yellow",
    // articleBackground: "#142e33",
    articleCardBackground: "#064854",
    articleHeading: "#061754",
  },
};
export default AppTheme;
